name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    name: Generate Keystore File
    runs-on: ubuntu-latest

    steps:
    - name: Generate keystore
      run: |
        keytool -genkey -v \
          -keystore my-release-key.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias my-key-alias \
          -dname "CN=John Doe, OU=Development, O=MyCompany, L=New York, ST=NY, C=US" \
          -storepass "keystore-password" \
          -keypass "key-password"

    - name: Upload keystore as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-keystore
        path: my-release-key.jks
